[package]
name = "jason"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
lazy_static = "1.5.0"
chrono = "0.4.39"
serde_json = "1.0.138"
exdisj = { path="../exdisj-rs", features=["json"] }